import { ConnectButton, RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { WagmiConfig } from 'wagmi'
import { useAccount } from 'wagmi'
import NextHead from "next/head";
import type { AppProps } from 'next/app'
import Link from "next/link";

import { WagmiReads } from '../wagmi/WagmiReads'
import styles from './index.module.css'
import NavBar from '../components/nav/nav'

import { chains, config } from '../wagmi'
import { useEffect, useState } from 'react';

export default function Page() {
  const [mounted, setMounted] = useState(false)
  useEffect(() => setMounted(true), [])
  return (
    <>
      <NextHead>
        <title>MirrorMarket NFT Chain</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </NextHead>
      <main className={styles.main}>
        <WagmiConfig config={config}>
          <RainbowKitProvider chains={chains}>
            <NavBar />
            <div className={styles.container}>
              <h1 className={styles.header}>Welcome to the Mirror NFT L2</h1>
              <Link target="_blank" href="https://docs.optimism.io/stack/getting-started" rel="noreferrer" className={styles.linkStyle}>
                OP Stack
              </Link>
              <Link target="_blank" href="https://github.com/NFTEarth" rel="noreferrer" className={styles.linkStyle}>
                Mirror Chain Github
              </Link>
              {mounted && <><div className={styles.connectButtonStyle}>
                <ConnectButton />
              </div>
                <hr />
                <WagmiReads /></>}
            </div>
          </RainbowKitProvider>
        </WagmiConfig>
      </main>
    </>
  )
}
